In [3]:
#higher order functioning
def add(x):
    return x+1
def multiply(x):
    return x*1
def apply(func,x):
    return func(x)
result1 = apply(add,6)
result2 = apply(multiply,5)
print(result1)
print(result2)

7
5


In [4]:
#to create an empty tuple
empty_tuple=()
print("empty tuple:",empty_tuple)


empty tuple: ()


In [5]:
#creating tuple having integers
int_tuple=(4,6,8,10,12,14)
print("tuples with integers",int_tuple)

tuples with integers (4, 6, 8, 10, 12, 14)


In [6]:
#creating tuple objects of different data types


In [24]:
#program to show how to access tuple elements
tuple_ = ("a","b","c","d")
print(tuple_[0])
print(tuple_[1])
try:
    print(tuple_[5])
except Exception as e:
    print(e)

a
b
tuple index out of range


In [17]:
#trying to access elements through the index of floating data type
try:
    print(tuple_[1.0])
except Exception as e:
    print(e)

tuple indices must be integers or slices, not float


In [25]:
#creating a nested tuple
nested_tuple=("Tuple",[4,6,2,6],(6,2,6,7))
print(nested_tuple[0][2])
print(nested_tuple[1][2])

p
2


In [26]:
#python program to show how negative indexing works :
tuple_=("Python","Tuple","Ordered","Collection")
print("Element at -1 index:",tuple_[-1])
print("Elements between -4 and -1 are:",tuple_[-4:-1])

Element at -1 index: Collection
Elements between -4 and -1 are: ('Python', 'Tuple', 'Ordered')


In [29]:
#How slicing works
tuple_=("Python","Tuple","Ordered","Immutable","Collection","Objects")
print("Elements between indices 1 and 3:",tuple_[1:3])
print("Elements between indices 0 and -4:",tuple_[:-4])
print("Entire tuple:",tuple_[:])

Elements between indices 1 and 3: ('Tuple', 'Ordered')
Elements between indices 0 and -4: ('Python', 'Tuple')
Entire tuple: ('Python', 'Tuple', 'Ordered', 'Immutable', 'Collection', 'Objects')


In [33]:
#deleting the elements of python tuple
tuple_=("Python","Tuple","Ordered","Immutable","Collection","Objects")
try:
    del tuple_[3]
    print(tuple_)
except Exception as e:
    print(e)


'tuple' object doesn't support item deletion


In [35]:
#repetition in tuples
tuple_=("Python","Tuples")
print("Original tuple is:",tuple_)
tuple_=tuple_*3
print("New tuple is:",tuple_)

Original tuple is: ('Python', 'Tuples')
New tuple is: ('Python', 'Tuples', 'Python', 'Tuples', 'Python', 'Tuples')


In [36]:
#creating tuples
T1=(0,1,2,3,3,2,2,5,6,7,3,4)
T2=('python','java','python','HTML','java','python')
res= T1.count(2)
print('Count of 2 in T1 is:',res)
res= T1.count('java')
print('Count of java in T2 is:',res)


Count of 2 in T1 is: 3
Count of java in T2 is: 0


In [37]:
#creating tuple
Tuple_data=(0,1,2,3,3,1,2,5,6,7,3,4)
res=Tuple_data.index(3)
print('First occurence of 1 is',res)
res=Tuple_data.index(3,5)
print('First occurence of 1 after 4th index is:',res)

First occurence of 1 is 3
First occurence of 1 after 4th index is: 10


In [38]:
#performing membership test for tuples
tuple_=("Python","Tuple","Ordered","Immutable","Collection","Objects")
print('Tuple'in tuple_)
print('items'in tuple_)
print('Immutable'not in tuple_)
print('Items'not in tuple_)

True
False
False
True


In [39]:
#python to show how to iterate over tuple elements
tuple_=("Python","Tuple","Ordered","Immutable")
for item in tuple_:
    print(item)

Python
Tuple
Ordered
Immutable


In [40]:
#python program to show how to concatenate tuples
tuple_=("Python","Tuple","Ordered","Immutable")
print(tuple_+(4,5,6))

('Python', 'Tuple', 'Ordered', 'Immutable', 4, 5, 6)


In [41]:
Days=set(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
print(Days)
print(type(Days))
print("Looping through the set elements...")
for i in Days:
    print(i)
set3= {}
print(type(set3))
set4=set()
print(type(set4))

{'Thursday', 'Sunday', 'Tuesday', 'Wednesday', 'Saturday', 'Monday', 'Friday'}
<class 'set'>
Looping through the set elements...
Thursday
Sunday
Tuesday
Wednesday
Saturday
Monday
Friday
<class 'dict'>
<class 'set'>


In [44]:
Months=set(["Jan","Feb","Mar","Apr","May","June"])
print("/nprinting the original set...")
print(Months)
print("/nAdding other months to the set...");
Months.add("July");
Months.add("August");
print("/nPrinting the modified set...")
print(Months)
print("/nlooping through the set elements...")
for i in Months:
    print(i)

/nprinting the original set...
{'Mar', 'Jan', 'Feb', 'May', 'Apr', 'June'}
/nAdding other months to the set...
/nPrinting the modified set...
{'Mar', 'Jan', 'August', 'July', 'Feb', 'May', 'Apr', 'June'}
/nlooping through the set elements...
Mar
Jan
August
July
Feb
May
Apr
June


In [45]:
Months=set(["Jan","Feb","Mar","Apr","May","June"])
print("/nprinting the original set...")
print(Months)
print("/nupdating the original set...")
Months.update(["July","Aug","Sep","Oct"])
print(Months)

/nprinting the original set...
{'Mar', 'Jan', 'Feb', 'May', 'Apr', 'June'}
/nupdating the original set...
{'Sep', 'Aug', 'Mar', 'Jan', 'Oct', 'July', 'Feb', 'May', 'Apr', 'June'}


In [46]:
months=set(["Jan","Feb","Mar","Apr","May","June"])
print("/nprinting the original set...")
print(Months)
print("/nRemoving some months from the set...");
months.discard("January");
months.discard("May");
print("/nPrinting the modified set...")
print(months)
print("/nlooping through the set elements...")
for i in months:
    print(i)

/nprinting the original set...
{'Sep', 'Aug', 'Mar', 'Jan', 'Oct', 'July', 'Feb', 'May', 'Apr', 'June'}
/nRemoving some months from the set...
/nPrinting the modified set...
{'Mar', 'Jan', 'Feb', 'Apr', 'June'}
/nlooping through the set elements...
Mar
Jan
Feb
Apr
June


In [47]:
#union intersection
Days1={"Mon","Tue","Wed","Thur","Sun"}
Days2={"Fri","Sat","Sun"}
print(Days1|Days2)


{'Fri', 'Wed', 'Mon', 'Sat', 'Tue', 'Thur', 'Sun'}


In [48]:
#difference
Days1={"Mon","Tue","Wed","Thur","Sun"}
Days2={"Fri","Sat","Sun"}
print(Days1-Days2)

{'Mon', 'Thur', 'Wed', 'Tue'}


In [49]:
#superset and subset
Days1={"mon","tue","wed","thur"}
Days2={"mon","tue"}
Days3={"mon","tue","fri"}
#superset
print(Days1>Days2)
#subset
print(Days1<Days2)
#not equivalent
print(Days1==Days2)

True
False
False



# NUMPY

In [50]:
#to check the version
import numpy as np
print(np.__version__)

1.20.1


In [51]:
#to check installation
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [53]:
#for checking type
import numpy as np
arr=np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


# use  a tuple to create a Numpy array:

In [54]:
#1-D array
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [55]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [58]:
#2-D array 
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [60]:
#3-D array
import numpy as np
arr=np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [67]:
#5-D Array
import numpy as np
arr=np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [68]:
#GET THE FIRST ELEMENT FROM ARRAY
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [69]:
#getting 3rd and 4th elements from array
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [70]:
#access the element on the first row,second column:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [76]:
#slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [78]:
#return every element from 1 to 5:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [79]:
#return every element from the entire array:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]



# Data types in NumPy


In [1]:
#create an array with data type 4 bytes integer:
import numpy as np
arr= np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [2]:
#change the data type from float to integer 
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [3]:
#make a copy changing original array
arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
#iteration in 2-D array
arr= np.array([[1,2,3,],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [5]:
#iterate through every scaler element of the 2D array skipping 1 element
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [8]:
#stacking 
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
arr= np.stack((arr1,arr2,), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
#Split the array in 3 parts:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
#access the splitted arrays:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [11]:
#fin the indexes where the value is 4:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [12]:
#find the indexes where the values are even:
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [13]:
#sort the array:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [14]:
#create a filter array that will return only values higher than 42.
arr = np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [15]:
#generating 1-D array containing 100 values

from numpy import random
x=random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 7 7 7 7 3 7 7 3 7 7 7 3 5 5 7 5 3 7 7 7 7 7 7 5 7 5 3 7 5 7 3 7 7 7 7 5
 3 5 7 3 7 7 7 7 7 7 3 3 7 7 5 7 3 7 7 5 3 7 3 7 7 3 7 7 5 5 7 7 7 7 5 7 5
 7 7 5 7 7 7 7 7 7 7 7 7 7 3 5 5 7 7 7 7 7 7 5 7 5 7]
